// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyC0D9sgMxpVPVv_EjKwlwxs4fZHZX_ho',
    appId: '1:1072696479894:web:97e0263686ad8e5150b2b7',
    messagingSenderId: '1072696479894',
    projectId: 'gopeduli-4f028',
    authDomain: 'gopeduli-4f028.firebaseapp.com',
    storageBucket: 'gopeduli-4f028.firebasestorage.app',
    measurementId: 'G-YQ1PRD2ME1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByi5Mz2ND8UgCQY5tuRTZRtbbwJA_UvEQ',
    appId: '1:1072696479894:android:72267b742c7e256450b2b7',
    messagingSenderId: '1072696479894',
    projectId: 'gopeduli-4f028',
    storageBucket: 'gopeduli-4f028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgu4NZzNl8S0SPhOSt12WpsKGHvFdSiSU',
    appId: '1:1072696479894:ios:963cbbf87bd4f4c250b2b7',
    messagingSenderId: '1072696479894',
    projectId: 'gopeduli-4f028',
    storageBucket: 'gopeduli-4f028.firebasestorage.app',
    iosBundleId: 'com.example.gopeduli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgu4NZzNl8S0SPhOSt12WpsKGHvFdSiSU',
    appId: '1:1072696479894:ios:963cbbf87bd4f4c250b2b7',
    messagingSenderId: '1072696479894',
    projectId: 'gopeduli-4f028',
    storageBucket: 'gopeduli-4f028.firebasestorage.app',
    iosBundleId: 'com.example.gopeduli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyC0D9sgMxpVPVv_EjKwlwxs4fZHZX_ho',
    appId: '1:1072696479894:web:6452765f6244cf0e50b2b7',
    messagingSenderId: '1072696479894',
    projectId: 'gopeduli-4f028',
    authDomain: 'gopeduli-4f028.firebaseapp.com',
    storageBucket: 'gopeduli-4f028.firebasestorage.app',
    measurementId: 'G-9NQTFEWWWQ',
  );

}